### ISSUE TITLE
Could not resolve location of module 'std/stdio'

### ISSUE THREAD

**Issue by Beiri22** [intellij-dlanguage/intellij-dlanguage#457] opened 2018-07-13 17:35 UTC
I just started with D and the IntelliJ-Plugin 1.17. I constantly get an warning/error-message "first.d:visit:418 Could not resolve location of module 'std/stdio'". I think it should find std/stdio, as the file is present. Does any have a clue how to solve that?

**Comment by andre2007** [comment] 2018-07-13 17:57
Which operating system do you use and where did you install DMD? Did you set the location of DMD in the project settings? For Linux you have to set the paths to Phobos manually in the DCD server flags fields. For Windows and MacOS the paths should be detected automatically if DMD SDK is set correctly in project settings.

**Comment by Beiri22** [comment] 2018-07-13 18:10
I am using Arch Linux and installed dmd via pacman (group dlang). The test programm does compile. The message described pops up independently while programming. Where do I set the pasths?

**Comment by andre2007** [comment] 2018-07-13 19:54
Please have a look here https://intellij-dlanguage.github.io (Configuring DCD)

**Comment by Beiri22** [comment] 2018-07-14 07:55
I have added the include-path /usr/include/dlang/dmd/ directly to the settings (dcd-server-flags). As far as I can see, there is no difference. Does DScanner read that setting? (Because the message comes from DScanner):
09:48	DScanner Error
			2018-07-14T09:48:25.568:first.d:visit:418 Could not resolve location of module 'std/stdio'
			

09:48	DScanner Error
			2018-07-14T09:48:25.568:first.d:visit:418 Could not resolve location of module 'std/format'

**Comment by andre2007** [comment] 2018-07-14 08:03
This field should contain the path to source/phobos and druntime/ import separated by a comma. If it not works please write exactly the value you used into this issue or add a screenshot.

**Comment by Beiri22** [comment] 2018-07-14 08:36
The only path I found was the following:
![bildschirmfoto vom 2018-07-14 10-34-55](https://user-images.githubusercontent.com/8210233/42722732-a9331c80-8751-11e8-9c68-b1dfe8b3bca9.png)

it contains the "missing" files and more:
du /usr/include/dlang/dmd/ -h
452K	/usr/include/dlang/dmd/core/stdc
16K	/usr/include/dlang/dmd/core/stdcpp
96K	/usr/include/dlang/dmd/core/internal
72K	/usr/include/dlang/dmd/core/sys/dragonflybsd/sys
24K	/usr/include/dlang/dmd/core/sys/dragonflybsd/netinet
116K	/usr/include/dlang/dmd/core/sys/dragonflybsd
48K	/usr/include/dlang/dmd/core/sys/darwin/mach
20K	/usr/include/dlang/dmd/core/sys/darwin/sys
24K	/usr/include/dlang/dmd/core/sys/darwin/netinet
104K	/usr/include/dlang/dmd/core/sys/darwin
296K	/usr/include/dlang/dmd/core/sys/posix/sys
12K	/usr/include/dlang/dmd/core/sys/posix/arpa
8,0K	/usr/include/dlang/dmd/core/sys/posix/net
52K	/usr/include/dlang/dmd/core/sys/posix/netinet
880K	/usr/include/dlang/dmd/core/sys/posix
68K	/usr/include/dlang/dmd/core/sys/solaris/sys
100K	/usr/include/dlang/dmd/core/sys/solaris
8,0K	/usr/include/dlang/dmd/core/sys/openbsd
3,1M	/usr/include/dlang/dmd/core/sys/windows
72K	/usr/include/dlang/dmd/core/sys/freebsd/sys
24K	/usr/include/dlang/dmd/core/sys/freebsd/netinet
116K	/usr/include/dlang/dmd/core/sys/freebsd
8,0K	/usr/include/dlang/dmd/core/sys/linux/sys/netinet
84K	/usr/include/dlang/dmd/core/sys/linux/sys
28K	/usr/include/dlang/dmd/core/sys/linux/netinet
264K	/usr/include/dlang/dmd/core/sys/linux
32K	/usr/include/dlang/dmd/core/sys/osx/mach
12K	/usr/include/dlang/dmd/core/sys/osx/sys
56K	/usr/include/dlang/dmd/core/sys/osx
4,7M	/usr/include/dlang/dmd/core/sys
32K	/usr/include/dlang/dmd/core/sync
6,0M	/usr/include/dlang/dmd/core
128K	/usr/include/dlang/dmd/etc/c/odbc
716K	/usr/include/dlang/dmd/etc/c/zlib
1,1M	/usr/include/dlang/dmd/etc/c
16K	/usr/include/dlang/dmd/etc/linux
1,1M	/usr/include/dlang/dmd/etc
672K	/usr/include/dlang/dmd/std/algorithm
456K	/usr/include/dlang/dmd/std/range
1,5M	/usr/include/dlang/dmd/std/datetime
460K	/usr/include/dlang/dmd/std/experimental/allocator/building_blocks
656K	/usr/include/dlang/dmd/std/experimental/allocator
144K	/usr/include/dlang/dmd/std/experimental/logger
940K	/usr/include/dlang/dmd/std/experimental
252K	/usr/include/dlang/dmd/std/internal/math
28K	/usr/include/dlang/dmd/std/internal/test
32K	/usr/include/dlang/dmd/std/internal/digest
8,0K	/usr/include/dlang/dmd/std/internal/windows
1,8M	/usr/include/dlang/dmd/std/internal
212K	/usr/include/dlang/dmd/std/digest
256K	/usr/include/dlang/dmd/std/regex/internal
316K	/usr/include/dlang/dmd/std/regex
68K	/usr/include/dlang/dmd/std/windows
248K	/usr/include/dlang/dmd/std/net
240K	/usr/include/dlang/dmd/std/container
11M	/usr/include/dlang/dmd/std
18M	/usr/include/dlang/dmd/

**Comment by andre2007** [comment] 2018-07-14 08:45
I do not have access to a Linux system at the moment. According to dcd read me.md there should following paths be used/usr/include/dmd/druntime/import
/usr/include/dmd/phobos

**Comment by Beiri22** [comment] 2018-07-14 08:55
These paths do not exist on my system. You can easily set up an arch linux like that:
	Use Antergos (https://antergos.com/) on virtualbox
	sudo pacman -S dlang
	when asked: select all
	sudo pacman -S intellij-idea-community-edition or install it via jetbrains-toolbox

The DScanner Error says:
	first.d:visit:418 Could not resolve location of module 'std/stdio'
	first.d:visit:418 Could not resolve location of module 'std/format'

They do both exist in the correct relative path to /usr/include/dlang/dmd:
	/usr/include/dlang/dmd/std/stdio.d
	/usr/include/dlang/dmd/std/format.d

They can even be opened in IntelliJ by CRTL-clicking a function name.

**Comment by andre2007** [comment] 2018-07-14 10:11
While the issue you facing is more related to setting up DCD correctly and less IntelliJ D plugin, manually setting up these paths should not be necessary. For windows and MacOS these paths are determined automatically by IntelliJ. See here https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServer.java#L172 If I can find out how the paths can be determined I will add this feature but I have only limited Linux/ dmd on Linux knowledge. There this will take some time.To help you, for the moment I can only suggest you create an issue on DCD repository to ask what are the right paths for your Linux system.

**Comment by Beiri22** [comment] 2018-07-14 11:05
1.) But is DCD and DScanner the same? I mean, the message comes from DScanner.
2.) The path I gave contains the files,  so where is the problem? I don't really get it.

**Comment by andre2007** [comment] 2018-07-14 11:34
I am sorry, I thought the issue is about DCD. 
  DCD -> Code completion
  DScanner -> Analyze D Code for issues

Same as DCD, DScanner also needs the paths to Phobos and DRuntime.  But please keep in mind, in contrast to the DCD server flags field, the paths in the DScanner flags field must be set this way -I path1 -I path2
(Exactly like you would call dscanner from the terminal)
You could also try to run dscanner from terminal: dscanner -I path1 -I path2 -S sourceCodeFile.d

This inconsistency between DScanner flags field and DCD server flags field will be solved in future.

**Comment by andre2007** [comment] 2018-07-14 18:14
By chance I just noticed that the D-Scanner Flags field is dead, the value is going nowhere. I will create a fix for that.

**Comment by Beiri22** [comment] 2018-07-14 18:37
On command line the argument -I works. I hope that the dead field will be fixed soon. There is something else, that might be related; but i'm not sure:

Given the following:
template person()
{
    private string name;
    private int age;
}

struct nametester
{
    mixin person;
}

==> code completion correctly shows the fields name and age in any instance of nametester.

But, given:
template person()
{
    private string name;
    private int age;
}

struct nametester
{
    mixin person mainCharacter;
    mixin person sideCharacter;
}

==> code completion does not show the aliases mainCharacter and sideCharacter in the instances of nametester, althought you need to use them to avoid naming conflicts.

Is this a related issue or worth a new ticket?

**Comment by andre2007** [comment] 2018-07-15 17:57
Code completion is provided by DCD. Purely DCD issues you can create on https://github.com/dlang-community/DCD.

I got the answer how to determine the Phobos/DRuntime folders on linux automatically (https://forum.dlang.org/thread/zaxxevfqycnuqgquafkn@forum.dlang.org).
I will implement this feature for DCD and for DScanner as additional Pull Requests.

**Comment by pirocks** [comment] 2018-07-15 19:10
> Code completion is provided by DCD.

Unless native code completion is enabled here:
![image](https://user-images.githubusercontent.com/10455020/42737381-2bb50b84-8827-11e8-8769-c97ebac57d05.png)

It is still experimental but could be used as an alternative to dcd.

**Comment by andre2007** [comment] 2018-07-17 19:05
https://github.com/intellij-dlanguage/intellij-dlanguage/pull/460

**Comment by andre2007** [comment] 2018-07-31 19:03
Pull request #460 was merged. With this pull request D-Scanner and DCD Server will add the sourcepaths defined in SDK (see screenshot above) as imports. 
There is also some logic already implemented in SDK to retrieve the correct phobos/druntime paths for all supported operation system.
In best case, by default now everything is working as expected.

**Comment by rainbow-alex** [comment] 2018-08-15 14:42
I just installed Intellij IDEA community edition and this plugin on linux; the source paths are correct by default and autocomplete for e.g. std.stdio is working! :+1:

**Comment by andre2007** [comment] 2019-01-06 21:32
@Beiri22 is the problem also solved for you?

**Comment by Beiri22** [comment] 2019-01-07 14:14
Sorry, in the meantime I have switched to vs code.

**Comment by andre2007** [comment] 2019-01-07 18:46
I think we can close this issue.

**Closed** 2019-01-08 01:30 UTC

**Comment by cschlote** [comment] 2023-05-05 08:28
DScanner v0.14.0 : It is 2023 now and the problem is back. Now for our Ubuntu-based CI pipelines  and our Arch-based local work hosts...

**Comment by SingingBush** [comment] 2023-05-05 10:09
is a valid path to dmd setup as an sdk and are the source paths correctly added (they should get picked up automatically but if not you can configure them)

**Comment by rikkimax** [comment] 2023-05-05 10:12
I have already asked Jan about this. Dscanner is not setup to receive said paths and hence this warning.

It was turned on due to a change with the logger in Phobos. It is harmless and should be ignored by the plugin.
