### ISSUE TITLE
Pressing tab on autocomplete clears all lines underneath expression

### ISSUE THREAD

**Issue by therealbluepandabear** [intellij-dlanguage/intellij-dlanguage#799] opened 2022-12-12 01:04 UTC
When I am suggested a particular method, enum, etc, like so:

![image](https://user-images.githubusercontent.com/50536495/206940614-61d1be16-b03b-4845-b84e-c3d1b003d903.png)

And then I press 'Tab', this is what happens:

![image](https://user-images.githubusercontent.com/50536495/206940531-64628ad8-25bc-4f25-8c54-330abb678442.png)

All of the lines below have been deleted.

This seems to happen whenever there is no right bracket for some reason.

As a sidenote, there also aren't the appropriate icons in some cases in autocompletion, I would have liked to see an enum icon for that particular autocompletion.

**Comment by rikkimax** [comment] 2022-12-12 04:02
Duplicate of #646

**Comment by therealbluepandabear** [comment] 2022-12-12 04:36
k my bad

**Closed** 2022-12-12 04:36 UTC
Labels: bug
