### ISSUE TITLE
"Possibly undefined symbol" for libraries imported via dub

### ISSUE THREAD

**Issue by bamarc** [intellij-dlanguage/intellij-dlanguage#263] opened 2017-10-30 23:15 UTC
All libraries i add via dub are not correctly indexed and without it the IDE is nearly unusable. Processing D libraries adds the paths to the project but does not seem to index them.
I tried reinstalling but that doesn't help either. 

System is OpenSuse Tumbleweed with the newest dmd and Intellij.

![screenshot_20171031_001037](https://user-images.githubusercontent.com/12558068/32200084-1e7ab418-bdd0-11e7-8eac-be28daf4f556.png)
![screenshot_20171031_001107](https://user-images.githubusercontent.com/12558068/32200085-1e9ba0d8-bdd0-11e7-8fdb-023ffd108a92.png)
![screenshot_20171031_001120](https://user-images.githubusercontent.com/12558068/32200086-1eb58f66-bdd0-11e7-9ab1-df415e0155b0.png)
![screenshot_20171031_001132](https://user-images.githubusercontent.com/12558068/32200087-1ed11ad8-bdd0-11e7-9251-89c3f9f8c25f.png)

**Comment by pirocks** [comment] 2017-10-31 09:13
Thanks for including pictures in your issue report.

If all else fails you can disable the possibly undefined symbol inspection via File>Settings>Editor>Inspections>Symbols>Possibly Undefined Symbol.

Here are a few things you can try to fix this problem:
1.File>Invalidate Caches/Restart > Invalidate and Restart (I would be surprised if this works, but its worth a try.)
2.Install a dev build of the plugin/build the plugin from source. I'm not sure exactly which version of the plugin you are using but this could be due to public imports not being handled correctly in older versions. ( @SingingBush, perhaps we could trigger an eap/dev build from my most recent PR?)
3. Try explicitly importing derelict.gl3.*. 
4. Revert to an older version of the plugin which doesn't have "Possibly undefined symbol"

Feel free to comment any other issues/suggestions/questions etc.

**Comment by bamarc** [comment] 2017-11-01 07:51
Number 3 worked which indicates a bug in the import logic. 

Do you have any suggestions for me to help and find it?

**Comment by pirocks** [comment] 2017-11-01 08:02
I'm already aware of it and I believe it is fixed in the develop branch. Unfortunately we do not have any very recent eap/dev builds,

**Comment by bamarc** [comment] 2017-11-01 11:12
I tried the develop branch and compiled it myself but to no effect. I switched off the error and enabled dcd for now.

**Comment by SingingBush** [comment] 2017-11-01 11:17
an EAP build was done on monday. see https://plugins.jetbrains.com/plugin/8115-d-language?pr=idea

**Comment by pirocks** [comment] 2017-11-01 13:34
>an EAP build was done on monday. see https://plugins.jetbrains.com/plugin/8115-d-language?pr=idea

Sorry, didn't realize that. 

>I tried the develop branch and compiled it myself but to no effect. I switched off the error and enabled dcd for now.

I seem to be unable to reproduce this behavior. Could you send me your dub.json?

>Number 3 worked which indicates a bug in the import logic.
>Do you have any suggestions for me to help and find it?

`io.github.intellij.dlanguage.psi.references.DReference#multiResolve` is the entry point for all symbol definition lookup(if no symbol definition is found then the symbol is "possibly undefined"). `io.github.intellij.dlanguage.resolve.processors.DNameScopeProcessor#handleImport` Is likely the method that is going wrong. It is supposed to get any symbols from a given statement(and any symbols publicly imported from there etc.).

**Comment by bamarc** [comment] 2017-11-01 14:05
I attached a test project in which the error occurs but it happens in every project i open/create. 
The dependencies get loaded by dub and added to the library list. I can even open the source files of the dependencies. 

It looks like the import is only loading the first file and not the whole package of the import. Even `string` is not recognized.

This is a screenshot using a develop build, run via `./gradlew runIde`
![error](https://user-images.githubusercontent.com/12558068/32278381-d4d2872c-bf15-11e7-8000-b4f0f6478de8.png)


[Test.zip](https://github.com/intellij-dlanguage/intellij-dlanguage/files/1434326/Test.zip)

**Comment by pirocks** [comment] 2017-11-01 16:00
I've reproduced the issue, I'll comment back here when I have a fix.

**Comment by pirocks** [comment] 2017-11-04 11:30
This bug make take longer than anticipated. It seems that if you manually use go to declaration on any of the highlighted symbols and step through the import logic with a debugger it finds the correct definition, however if you don't step through with the debugger it does not. This implies some kind of concurrency/lazy eval issue which will be harder to debug. It also appears that go to definition and highlighting works perfectly from library files. e.g. If I use go to definition on a symbol that is highlighted in app.d, from a library file, the correct definition is found.

**Comment by pirocks** [comment] 2017-11-08 14:15
Issue fix in pull request #268. @bamarc please confirm that this fixes the issue?

**Comment by bamarc** [comment] 2017-11-08 15:23
Code completion seems to be fixed, also no more possible undefined symbol errors, **except** for the import statements them self.

Only the upper layer of the import is marked as error, but nonetheless it's working. 

![screenshot_20171108_162056](https://user-images.githubusercontent.com/12558068/32556917-08cd06d4-c4a1-11e7-9d50-fb2352ba673c.png)


Thank you very much for your effort.

**Closed** 2017-11-08 15:24 UTC

**Comment by pirocks** [comment] 2017-11-08 19:56
The import statements are likely caused by an issue with Process D Libs. I'm working on resolving that issue.

>Thank you very much for your effort.

Thanks for providing the .zip, reporting the bug etc.
