### ISSUE TITLE
syntax highlight is different if param is var or literal

### ISSUE THREAD

**Issue by trikko** [intellij-dlanguage/intellij-dlanguage#83] opened 2016-01-19 12:10 UTC
![ss](https://cloud.githubusercontent.com/assets/647157/12418181/e42f4152-bead-11e5-868b-f9329fdb2bf3.png)

**Comment by kingsleyh** [comment] 2016-01-19 14:14
duplicate of issue #74 
I have a plan

**Comment by trikko** [comment] 2016-01-19 14:15
I checked that issue but it seems a different case :)

**Comment by pirocks** [comment] 2017-11-23 18:36
Syntax highlighting has changed a lot since this issue, and this is no longer relevant,

**Closed by pirocks** 2017-11-23 18:36 UTC
