### ISSUE TITLE
Plugin stops working after updating to Intellij 2019.3

### ISSUE THREAD

**Issue by the-Mitu** [intellij-dlanguage/intellij-dlanguage#539] opened 2019-11-29 07:39 UTC
It is a major problem, that every time IntelliJ updates to the new minor release, the D plugin turns off until the next version of it is released. Would it be possible to adjust the compatibility to the upcoming IDE release, so there was no such problem?

I know I can always put off updating my IDE, but it would be nice not having to.

**Comment by SingingBush** [comment] 2019-11-29 08:50
duplicate of #521 

Now that 2019.3 had had a final build I'll add the release build to the build jobs. The plugin will not get marked as 2019.3 compatible unless tests pass against that version.

**Closed by SingingBush** 2019-11-29 08:50 UTC
