### ISSUE TITLE
empty multi line comments with whitespace breaks the syntax highlighting lexer

### ISSUE THREAD

**Issue by therealbluepandabear** [intellij-dlanguage/intellij-dlanguage#771] opened 2022-11-05 00:24 UTC
Your plugin is fantastic, but there is a major syntax highlighting bug.

I am using the latest version of this plugin in IntelliJ IDEA, and I have observed major syntax highlighting bugs:

![image](https://user-images.githubusercontent.com/50536495/200092347-97f76882-0613-4c87-9bca-d7064f72c2c1.png)

![image](https://user-images.githubusercontent.com/50536495/200092355-997d71a6-c866-4b43-9169-210f1f708ca7.png)

![image](https://user-images.githubusercontent.com/50536495/200094487-7b81b48f-bf13-4709-b5da-fdf3ca6b718f.png)

**This only really gets fixed if you restart the IDE, or just delete the whole code and paste it in again, I think this simply forces a new recalculation of the syntax highlighting.**

Please consider looking into this.

**Comment by SingingBush** [comment] 2022-11-05 09:48
Could you set the log level for `io.github.intellij.dlanguage` to debug and then, after encountering the problem, paste the content of your IDEA log into a comment. Alternatively clone the project and use `./gradlew runIde` to run the project in a sandboxes ide to see what errors are occurring.

**Comment by therealbluepandabear** [comment] 2022-11-05 12:28
> Could you set the log level for `io.github.intellij.dlanguage` to debug and then, after encountering the problem, paste the content of your IDEA log into a comment. Alternatively clone the project and use `./gradlew runIde` to run the project in a sandboxes ide to see what errors are occurring.

Of course. I will get back to you soon.

**Comment by therealbluepandabear** [comment] 2022-11-05 22:27
Hello -- apologies for getting back to you late,

When I recreated the issue, IntelliJ notified me of an exception within your plugin with the following stacktrace:

```
nonempty text is not covered by block in #D #formatter
Range: [51,61], text fragment: [51,61]


com.intellij.diagnostic.PluginException:  [Plugin: net.masterthought.dlanguage]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.formatting.RangesAssert.assertInvalidRanges(RangesAssert.java:60)
	at com.intellij.formatting.WhiteSpace.changeEndOffset(WhiteSpace.java:127)
	at com.intellij.formatting.engine.WrapBlocksState.getLastWhiteSpace(WrapBlocksState.java:71)
	at com.intellij.formatting.FormatProcessor.getLastWhiteSpace(FormatProcessor.java:401)
	at com.intellij.formatting.FormatterImpl.getWhiteSpaceAtOffset(FormatterImpl.java:508)
	at com.intellij.formatting.FormatterImpl.generateIndentWhitespace(FormatterImpl.java:492)
	at com.intellij.formatting.FormatterImpl.getLineIndent(FormatterImpl.java:461)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$4.doPerform(CodeStyleManagerImpl.java:319)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$4.doPerform(CodeStyleManagerImpl.java:311)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:93)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.getLineIndent(CodeStyleManagerImpl.java:321)
	at com.intellij.psi.impl.source.codeStyle.lineIndent.FormatterBasedLineIndentProvider.getLineIndent(FormatterBasedLineIndentProvider.java:42)
	at com.intellij.application.options.CodeStyle.getLineIndent(CodeStyle.java:446)
	at com.intellij.codeInsight.editorActions.EnterHandler.adjustLineIndentNoCommit(EnterHandler.java:311)
	at com.intellij.codeInsight.editorActions.EnterHandler$DoEnterAction.run(EnterHandler.java:436)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteActionInner(EnterHandler.java:162)
	at com.intellij.codeInsight.editorActions.EnterHandler.lambda$executeWriteAction$0(EnterHandler.java:64)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.lambda$disablePostprocessFormattingInside$2(PostprocessReformattingAspect.java:120)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:128)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:63)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:66)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:202)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:66)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$2(EditorActionHandler.java:192)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$3(EditorActionHandler.java:191)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:312)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:421)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:321)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:296)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:189)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerSmartStepIntoHandler$SmartStepEditorActionHandler.doExecute(XDebuggerSmartStepIntoHandler.java:417)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:63)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:93)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:102)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:77)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:714)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:658)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:606)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:489)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:229)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Current context:

```
Fragment text: '
	/*
	
}

'
File text:(61)
'import std.stdio;
import std.random;

void main() {
	/*
	
}

'
model (class com.intellij.psi.formatter.FormattingDocumentModelImpl): com.intellij.psi.formatter.FormattingDocumentModelImpl@395167fPsi Tree:
Root D Language File(0,61)
  DLanguageDeclarationImpl(DECLARATION)(0,17)
    DLanguageImportDeclarationImpl(IMPORT_DECLARATION)(0,17)
      PsiElement(DlangTokenType.import)('import')(0,6)
      PsiWhiteSpace(' ')(6,7)
      SINGLE_IMPORT(7,16)
        DLanguageIdentifierChainImpl(IDENTIFIER_CHAIN)(7,16)
          IDENTIFIER(7,10)
            PsiElement(DlangTokenType.ID)('std')(7,10)
          PsiElement(DlangTokenType..)('.')(10,11)
          IDENTIFIER(11,16)
            PsiElement(DlangTokenType.ID)('stdio')(11,16)
      PsiElement(DlangTokenType.;)(';')(16,17)
  PsiWhiteSpace('\n')(17,18)
  DLanguageDeclarationImpl(DECLARATION)(18,36)
    DLanguageImportDeclarationImpl(IMPORT_DECLARATION)(18,36)
      PsiElement(DlangTokenType.import)('import')(18,24)
      PsiWhiteSpace(' ')(24,25)
      SINGLE_IMPORT(25,35)
        DLanguageIdentifierChainImpl(IDENTIFIER_CHAIN)(25,35)
          IDENTIFIER(25,28)
            PsiElement(DlangTokenType.ID)('std')(25,28)
          PsiElement(DlangTokenType..)('.')(28,29)
          IDENTIFIER(29,35)
            PsiElement(DlangTokenType.ID)('random')(29,35)
      PsiElement(DlangTokenType.;)(';')(35,36)
  PsiWhiteSpace('\n\n')(36,38)
  DLanguageDeclarationImpl(DECLARATION)(38,61)
    FUNCTION_DECLARATION(38,61)
      DLanguageTypeImpl(TYPE)(38,42)
        DLanguageType_2Impl(TYPE_2)(38,42)
          DLanguageBuiltinTypeImpl(BUILTIN_TYPE)(38,42)
            PsiElement(DlangTokenType.void)('void')(38,42)
      PsiWhiteSpace(' ')(42,43)
      IDENTIFIER(43,47)
        PsiElement(DlangTokenType.ID)('main')(43,47)
      DLanguageParametersImpl(PARAMETERS)(47,49)
        PsiElement(DlangTokenType.()('(')(47,48)
        PsiElement(DlangTokenType.))(')')(48,49)
      PsiWhiteSpace(' ')(49,50)
      DLanguageFunctionBodyImpl(FUNCTION_BODY)(50,61)
        DLanguageSpecifiedFunctionBodyImpl(SPECIFIED_FUNCTION_BODY)(50,61)
          DLanguageBlockStatementImpl(BLOCK_STATEMENT)(50,61)
            PsiElement(DlangTokenType.{)('{')(50,51)
            PsiWhiteSpace('\n')(51,52)
            PsiWhiteSpace('\t/*\n\t\n}\n\n')(52,61)
            DLanguageDeclarationsAndStatementsImpl(DECLARATIONS_AND_STATEMENTS)(61,61)
              <empty list>
            PsiErrorElement:Expected } instead of EOF(61,61)
              <empty list>
```

Hopefully this is enough info!

**Comment by SingingBush** [comment] 2022-11-06 21:26
thanks for digging into it. seems that multiline comments that only have whitespace are in need of attention. I amended the `DlangHighlightingLexerTest::testcomment_multi()` method to test for:

```
/*
 multiline comment
 is here
 */

/**/

/*
*
*/

/*

*/
```

with the expected outcome of

```
DlangTokenType.BLOCK_COMMENT ('/*\n multiline comment\n is here\n */')
WHITE_SPACE ('\n\n')
DlangTokenType.BLOCK_COMMENT ('/**/')
WHITE_SPACE ('\n\n')
DlangTokenType.BLOCK_COMMENT ('/*\n*\n*/')
WHITE_SPACE ('\n\n')
DlangTokenType.BLOCK_COMMENT ('/*\n\n*/')
```

that works initially but if I add a space or tab to that last comment block and run the test again it breaks the test. This'll need some more time spent on it to get a fix in place

**Comment by therealbluepandabear** [comment] 2022-11-06 22:55
Thanks! When I get more experienced with D I would like to contribute to this project.

Just a reminder that the issue is also reproducible with `writeln` statements as well, not just comments.

**Comment by etienne02** [comment] 2022-11-08 13:35
I’m able to reproduce the issue. Closing the file and reopening it make the highlighting correct again without having to close the IDE.

I changed the test to add you cases, and if the test becomes wrong when you add space, it’s simply because the expected result need to be updated too. If you add a space to the expected file, test pass correctly.
I can open a pull request to add them if you want.

**Comment by etienne02** [comment] 2022-11-09 19:57
@therealbluepandabear https://github.com/intellij-dlanguage/intellij-dlanguage/pull/772 should fix your problem, if you want to test it, feel free.

**Comment by therealbluepandabear** [comment] 2022-11-10 04:31
> @therealbluepandabear #772 should fix your problem, if you want to test it, feel free.

Thanks for this, I will definitely test it out.

Will get back soon.

**Closed** 2022-11-10 21:41 UTC
Labels: bug, help wanted, parser

**Comment by therealbluepandabear** [comment] 2022-11-10 22:39
I saw that you guys merged the pull request -- this is fine because you guys have already done massive bugfixes in that branch. I will try to reproduce the bug I had again and if it still occurs I will make a new issue for it. Thanks.
