### ISSUE TITLE
Occasional exception on Git Commit/Push

### ISSUE THREAD

**Issue by caspervg** [intellij-dlanguage/intellij-dlanguage#71] opened 2016-01-13 15:51 UTC
Every so often (about 1/3 times I use IntelliJ's git commit & push functionality), an "internal IDE error" occurs with the following stacktrace.

```
Calling invokeAndWait from read-action leads to possible deadlock.
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:721)
    at net.masterthought.dlanguage.highlighting.annotation.external.DExternalAnnotator.doAnnotate(DExternalAnnotator.java:45)
    at net.masterthought.dlanguage.highlighting.annotation.external.DExternalAnnotator.doAnnotate(DExternalAnnotator.java:21)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.f(ExternalToolPass.java:218)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.getInfos(ExternalToolPass.java:137)
    at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.runMainPasses(DaemonCodeAnalyzerImpl.java:270)
    at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl$5$1.run(CodeSmellDetectorImpl.java:172)
    at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:123)
    at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:117)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
    at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:117)
    at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl$5.run(CodeSmellDetectorImpl.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl.a(CodeSmellDetectorImpl.java:161)
    at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl.access$100(CodeSmellDetectorImpl.java:55)
    at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl$3.run(CodeSmellDetectorImpl.java:129)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:626)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

I'm not able to consistently reproduce it, but I have had it happen about 5 times now.

**Comment by kingsleyh** [comment] 2016-01-14 19:26
I suspect this is something to do with the external annotators trying to read a file during a git transaction - I think I can fix this by using a read lock - I will investigate

**Comment by pirocks** [comment] 2017-11-29 14:30
Related/duplicate of #232. This should be fixed.

**Closed by pirocks** 2017-11-29 14:30 UTC
